export const API_CONSTANTS: any = {
    adminLogin : 'authorization/users/login',
    menu : 'ResourcePermission/GetMenusList?userId={userId}&roleId={role}',
    country : 'Common/GetCountryDropdownList',
    state: 'Common/GetStateDropdownList?countryId={countryID}',
    city: 'Common/GetDistrictDropdownList?countryId={countryID}&stateId={stateID}',
    company : 'Common/GetCompanyDropdownList?userId={userID}',
    resourceGroup:'Common/GetResourceGroupDropdownList',
    resourceMasterList:'master/resourceList',
    parentResourceDropdown:'master/resourceList',
    roleMasterList:'master/roleList',
    roleMasterDropdownList:'master/roleList',
    resourcePermissionList:'master/resourcePermissonList',
    resourceGroupList:'master/resourceGroupList',
    addRole:'master/createRole',
    addResourceMaster:'master/createResource',
    addResourceGroup:'master/addResourceGroup',
    companyList:'master/companyList',
    companyDropdown:'master/companyList',
    createCompany:'master/createCompany',
    userMasterList:'user/adminUserList',
    createUserMaster:'user/addAdminUser',
    vehicleList:'vehicle/vehicleMasterList',
    vehicleTypeDropdown:'vehicle/vehicleTypeList',
    userDropdown:'user/adminUserList',
    createVehicle:'vehicle/addVehicle',
    deleterole:'master/deleteRole/{roleId}',
    updateVehicle : 'vehicle/updateVehicle/{vehicleId}',
    resourceForPermission : 'master/resorceForPermission/{roleId}',
    updateRole : 'master/updateRole/{roleId}',
    updateResourceGroup : 'master/updateResourceGroup/{resourceGroupId}',
    deleteResourceGroup:'master/deleteResourceGroup/{resourceGroupId}',
    deleteVehicle:'vehicle/deleteVehicle/{VehicleId}',
    deleteCompany:'master/deleteCompany/{compId}',
    deleteUser:'user/deleteUser/{userId}',
    deleteResourceMaster:'master/deleteResource/{resourceId}',
    addPermission : 'master/addResourcePermisson',
    customerDevice : 'device/customerDeviceList',
    updateCompany:'master/updateCompany/{compId}',
    updateResourceMaster:'master/updateResource/{resourceId}',
    deviceType : 'device/deviceTypeList',
    vehicleType: 'vehicle/vehicleTypeList',
    addCustomerDevice:'device/addCustomerDevice',
    updateDevice :'device/updateDevice/{deviceId}',
    deleteDevice :'device/deleteDevice/{deviceId}',
    updateUser : 'user/updateUser/{userId}',
    locationDetails : 'address/getLocationList'

}